### ISSUE TITLE
后台服务器端问题

### ISSUE THREAD

**Issue by Butterlor** [Chdolce/Airbnb#1]
你们的后台是用什么框架去写的，能提供一下源码和设计方法吗

**Comment by Irisleaf** [comment]
我们所有的代码都在这里了。你的意思是数据库和前端的连接吗

**Comment by Butterlor** [comment]
对的，后台数据库和前段的交互


 
---原始邮件---
发件人: "Irisleaf"<notifications@github.com>
发送时间: 2019年6月3日(星期一) 下午4:04
收件人: "Chdolce/Airbnb"<Airbnb@noreply.github.com>;
抄送: "Butterlor"<973905413@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [Chdolce/Airbnb] 后台服务器端问题 (#1)



我们所有的代码都在这里了。你的意思是数据库和前端的连接吗

**Comment by Butterlor** [comment]
我还想请问一下你们的后台是用java写的吗，具体的模式是怎么样的，想了解一下


 
---原始邮件---
发件人: "Irisleaf"<notifications@github.com>
发送时间: 2019年6月3日(星期一) 下午4:04
收件人: "Chdolce/Airbnb"<Airbnb@noreply.github.com>;
抄送: "Butterlor"<973905413@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [Chdolce/Airbnb] 后台服务器端问题 (#1)



我们所有的代码都在这里了。你的意思是数据库和前端的连接吗

**Comment by Irisleaf** [comment]
用jsp连接的，所有代码都在上面了，jsp从数据库里读取，安卓页面交互用JSON解析

**Comment by Butterlor** [comment]
想看一下你们后台的源码，如果方便的话

**Comment by Butterlor** [comment]
你们的后台是用Java写的是吗

**Comment by Butterlor** [comment]
你们的后台用什么框架进行开发的，比如SSH或者Spring MVC之类的，能分享一下吗

**Comment by Irisleaf** [comment]
我们所谓的后台只有和数据库的连接，管理员所使用的的后台我们并没有写，所以后台并没有开发框架，是用java写的，具体技术请参考《第一行代码》

**Comment by Butterlor** [comment]
第一行代码好项目没有讲如何用Java开发Web服务器端的知识呀，而且我还不会怎么去编写和部署到服务器上WWWWW.....

**Comment by Irisleaf** [comment]
好吧，重点是我们的项目也没有用服务器，我们是用http协议连接的

**Comment by Irisleaf** [comment]
具体可参考https://www.cnblogs.com/double1/p/5837926.html

**Comment by Butterlor** [comment]
hhhh好吧。可是你们的课设报告里面不是有关于服务器的架构设计吗，而且你们上传的源码也有类似于服务器端的代码




------------------ 原始邮件 ------------------
发件人: "Irisleaf"<notifications@github.com>;
发送时间: 2019年6月18日(星期二) 晚上8:10
收件人: "Chdolce/Airbnb"<Airbnb@noreply.github.com>;
抄送: "李甲衍"<973905413@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [Chdolce/Airbnb] 后台服务器端问题 (#1)




好吧，重点是我们的项目也没有用服务器，我们是用http协议连接的

**Comment by Irisleaf** [comment]
诶我也不知道怎么说，我们写的时候想的挺简单的，你这样提问就感觉我们写的很复杂。。。

**Comment by Butterlor** [comment]
那你们的那些图片资源是储存在哪里的呀




------------------ 原始邮件 ------------------
发件人: "Irisleaf"<notifications@github.com>;
发送时间: 2019年6月18日(星期二) 晚上8:17
收件人: "Chdolce/Airbnb"<Airbnb@noreply.github.com>;
抄送: "李甲衍"<973905413@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [Chdolce/Airbnb] 后台服务器端问题 (#1)




诶我也不知道怎么说，我们写的时候想的挺简单的，你这样提问就感觉我们写的很复杂。。。

**Comment by Irisleaf** [comment]
图片以网址形式存储在数据库中
mysql建表语句：
CREATE TABLE `apartmentss` (
  `hid` varchar(10) NOT NULL,
  `title` varchar(255) NOT NULL,
  `country` varchar(255) DEFAULT NULL,
  `province` varchar(255) DEFAULT NULL,
  `city` varchar(255) DEFAULT NULL,
  `latitude` double(42,20) DEFAULT NULL,
  `longtitude` double(42,20) DEFAULT NULL,
  `type` varchar(255) DEFAULT NULL,
  `guests_count` int(11) DEFAULT NULL,
  `info` varchar(511) DEFAULT NULL,
  `refer_price` int(11) DEFAULT NULL,
  `picture` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`hid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 
（这张表好像不是最终的表，后来有建另一个库，思路差不多就是这样）

**Comment by Butterlor** [comment]
意思是你们的图片都是从一些网站上面通过http协议抓取然后显示到手机APP上面的是吗


------------------ 原始邮件 ------------------
发件人: "Irisleaf"<notifications@github.com>;
发送时间: 2019年6月18日(星期二) 晚上8:23
收件人: "Chdolce/Airbnb"<Airbnb@noreply.github.com>;
抄送: "李甲衍"<973905413@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [Chdolce/Airbnb] 后台服务器端问题 (#1)




图片以网址形式存储在数据库中
 mysql建表语句：
 CREATE TABLE apartmentss (
 hid varchar(10) NOT NULL,
 title varchar(255) NOT NULL,
 country varchar(255) DEFAULT NULL,
 province varchar(255) DEFAULT NULL,
 city varchar(255) DEFAULT NULL,
 latitude double(42,20) DEFAULT NULL,
 longtitude double(42,20) DEFAULT NULL,
 type varchar(255) DEFAULT NULL,
 guests_count int(11) DEFAULT NULL,
 info varchar(511) DEFAULT NULL,
 refer_price int(11) DEFAULT NULL,
 picture varchar(255) DEFAULT NULL,
 PRIMARY KEY (hid)
 ) ENGINE=InnoDB DEFAULT CHARSET=utf8
 （这张表好像不是最终的表，后来有建另一个库，思路差不多就是这样）

**Comment by Irisleaf** [comment]
不是 我们http协议用来连接安卓端和服务器的（我们的服务器就是自己的电脑）（图片是放在自己的数据库里读取的）
关于服务器我们没有使用云服务器（你要是想问怎么连接云服务器我们也不知道）

**Comment by Irisleaf** [comment]
All done
